name: Cypress

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env: 
  PR_NUMBER: ${{ github.event.number }}
  BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
  NETLIFY_SITE_ID: ${{ vars.NETLIFY_SITE_ID }}
  NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
  UPDATED_AT: ${{ github.event.pull_request.updated_at }}
  COMMIT_SHA: $ {{ github.event.pull_request.head.sha }}


jobs:
  cypress-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn

      - name: Run Cypress
        run: |
              output=$(node .github/workflows/scripts/wait-for-netlify-deploy.js 2>&1)
              exit_code=$?

              # Check if the process exited with a non-zero status
              if [ $exit_code -ne 0 ]; then
                  echo "The process exited with a non-zero status: $exit_code"
                  exit $exit_code
              fi

              CYPRESS_BASE_URL=$(echo "$output" | grep -o 'Deploy URL: http://[^ ]*' | awk '{print $3}') yarn test:cypress:ci

