name: Lint and Types Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-and-types:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Run Lint
        run: npm run lint

      - name: Run Types Check
        run: npm run types
